### ISSUE TITLE
Link dataset 

### ISSUE THREAD

**Issue by C0NGTRI123** [liweim/TextLayoutLLM#1]
Can you public link dataset, I can't see dataset to lookup :)

**Comment by liweim** [comment]
Hi,

You can download the dataset from this link: https://www.alipan.com/s/v6FrwXjq166
I also updated the README and provided the link.

Best,
Weiming
________________________________
From: ***@***.*** ***@***.***> on behalf of congtri ***@***.***>
Sent: Friday, July 19, 2024 8:41 PM
To: liweim/TextLayoutLLM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [liweim/TextLayoutLLM] Link dataset (Issue #1)


Can you public link dataset, I can't see dataset to lookup :)

**Comment by C0NGTRI123** [comment]
Can you update in drive, onedrive or dropbox. I don't have account to download your dataset :(.

**Comment by liweim** [comment]
Here is it: https://drive.google.com/drive/folders/1w8LD-gfskhn_rK8dxO5WZ4LPqRY4HPDQ?usp=sharing
















At 2024-07-24 12:15:35, "congtri" ***@***.***> wrote:

Can you update in drive, onedrive or dropbox. I don't have account to download your dataset :(.

**Comment by C0NGTRI123** [comment]
Thank you!!!!!!!!
